/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import edd.Matriz;
import static gui.AgregarCiudadesGUI.interfazB;

/**
 *
 * @author Sofia
 */
public class EliminarCiudades extends javax.swing.JFrame {
    private Matriz grafo;
    private String[] deletable ; 
    public static EditCuidadesGUI interfazA;
    
    /**
     * Creates new form EliminarCiudades
     */
    public EliminarCiudades(EditCuidadesGUI interfazA) {
        initComponents();
        this.interfazA= interfazA;
        interfazA.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
            
    
    public EliminarCiudades(Matriz grafo) {
        initComponents();
        this.grafo = grafo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        notify = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ciudades = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(notify, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        ciudades.setEditable(false);
        ciudades.setColumns(20);
        ciudades.setRows(5);
        jScrollPane1.setViewportView(ciudades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 80, 210));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliminar ciudades");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        eliminar.setBackground(new java.awt.Color(102, 51, 0));
        eliminar.setFont(new java.awt.Font("Adobe Devanagari", 0, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, -1));

        jLabel3.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Posibles ciudades a eliminar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Volver.setBackground(new java.awt.Color(102, 51, 0));
        Volver.setFont(new java.awt.Font("Adobe Devanagari", 0, 12)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2024-02-18 at 12.14.25 PM.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 380, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
       String x = this.input.getText();
       if (x.isBlank()) {
           this.notify.setText("Por favor, ingrese una ciudad");
       } else if (this.deletable.length == 0){
           this.notify.setText("No puede borrar ciudades, se encuentra en el limite minimo de ciudades");
       } else {
           for (String c: this.deletable) {
               x.replace(" ", ""); 
               if (c == x) {
                   this.grafo.eliminarVertice(x);
               } else {
                   this.notify.setText("Por favor entre una ciudad valida.");
               }
           }
       }
    }//GEN-LAST:event_eliminarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        EditCuidadesGUI interfazD= new EditCuidadesGUI(this);
        Matriz grafoUpdated = grafo;
        
    }//GEN-LAST:event_VolverActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudadesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCiudadesGUI(interfazA).setVisible(true);
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    public void start () throws Exception {
        if (this.grafo.getNumVerts() <= 4) {
            this.notify.setText("Solo puede eliminar ciudades si hay más de cuatro ciudades existentes");
            this.deletable =  new String[0]; 
        } else {
            this.deletable = this.grafo.nonBridgeds();
            String show = ""; 
            int counter = 1; 
            if (this.deletable.length == 0) {
                show = "Ninguna ciudad puede ser eliminada";
            }else {
                for (String c: this.deletable) {
                show += counter + "-  " +c + "\n"; 
                counter++; 
            }
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            this.ciudades.setText(show);
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JTextArea ciudades;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notify;
    // End of variables declaration//GEN-END:variables
}
