/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import edd.Matriz;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class IniciarSimulacionGUI extends javax.swing.JFrame {
    
    public static ValoresInicialesGUI interfaz5a;
    private Matriz grafo; 
    private double alpha, beta, gamma; 
    private int antn, cycles; 
    private String ciudadi, ciudadf; 

    /**
     * Creates new form IniciarSimulacionGUI
     */
    public IniciarSimulacionGUI(ValoresInicialesGUI interfaz5a, String ciudadi, String ciudadf, int cycles, int antn, double a, double b, double p) {
        initComponents();
        this.setResizable(false);
        this.interfaz5a = interfaz5a;
        this.grafo = interfaz5a.getGrafo();
        interfaz5a.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.ciudadi = ciudadi;
        this.ciudadf = ciudadf;
        this.cycles = cycles;
        this.antn = antn;
        this.alpha = a;
        this.beta = b;
        this.gamma = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IniciarSimulacion = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desea iniciar la simulacion?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 243, 37));

        jLabel2.setFont(new java.awt.Font("Adobe Devanagari", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOTA: al presionar el boton no podra cambiar los valores agregados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, 70));

        IniciarSimulacion.setBackground(new java.awt.Color(102, 0, 0));
        IniciarSimulacion.setFont(new java.awt.Font("Adobe Devanagari", 0, 14)); // NOI18N
        IniciarSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSimulacion.setText("Iniciar");
        IniciarSimulacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSimulacionActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 60));

        Volver.setBackground(new java.awt.Color(102, 51, 0));
        Volver.setFont(new java.awt.Font("Adobe Devanagari", 0, 14)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("<<Volver");
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2024-02-18 at 12.14.25 PM.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 520, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSimulacionActionPerformed
        try {
            CiclosGUI interfaz5b = new CiclosGUI(this, this.ciudadi, this.ciudadf, this.cycles, this.antn, this.alpha, this.beta, this.gamma);
        } catch (Exception ex) {
            Logger.getLogger(IniciarSimulacionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IniciarSimulacionActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        ValoresInicialesGUI interfaz4back = new ValoresInicialesGUI(this);
    }//GEN-LAST:event_VolverActionPerformed

    public Matriz getGrafo() {
        return grafo;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarSimulacion;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
