
package gui;

public class ValoresInicialesGUI extends javax.swing.JFrame {

    public static EditorTxtGUI interfaz2;
    
    public ValoresInicialesGUI(EditorTxtGUI interfaz2) {
        initComponents();
        this.interfaz2 = interfaz2;
        interfaz2.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gama = new javax.swing.JTextField();
        alpha1 = new javax.swing.JTextField();
        hormigas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        beta2 = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        numciclos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setText("Valores Iniciales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));

        jLabel2.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabel2.setText("α");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 40, -1));

        jLabel3.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabel3.setText("Alpha ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabel4.setText("Numero de Hormigas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        gama.setText("0");
        gama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamaActionPerformed(evt);
            }
        });
        jPanel1.add(gama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        alpha1.setText("0");
        alpha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alpha1ActionPerformed(evt);
            }
        });
        jPanel1.add(alpha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        hormigas.setText("0");
        hormigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hormigasActionPerformed(evt);
            }
        });
        jPanel1.add(hormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabel5.setText("Beta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        beta2.setText("0");
        beta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beta2ActionPerformed(evt);
            }
        });
        jPanel1.add(beta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        next.setText("Continuar>>");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 110, 30));

        jLabel7.setFont(new java.awt.Font("Adobe Devanagari", 0, 16)); // NOI18N
        jLabel7.setText("Numero de Ciclos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        numciclos.setText("0");
        numciclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numciclosActionPerformed(evt);
            }
        });
        jPanel1.add(numciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamaActionPerformed

    private void alpha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alpha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alpha1ActionPerformed

    private void hormigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hormigasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hormigasActionPerformed

    private void beta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beta2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void numciclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numciclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numciclosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresInicialesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresInicialesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresInicialesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresInicialesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresInicialesGUI(interfaz2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alpha1;
    private javax.swing.JTextField beta2;
    private javax.swing.JTextField gama;
    private javax.swing.JTextField hormigas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JTextField numciclos;
    // End of variables declaration//GEN-END:variables
}
